<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-O4BFA6G" failures="2" tests="2" name="ErrorValidation Test" time="14.004" errors="0" timestamp="2024-06-01T02:50:51 IST">
  <testcase classname="testcases.ErrorValidation" name="ErrorTest" time="0.702">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.##] but found [Incorrect email or password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.##] but found [Incorrect email or password.]
at testcases.ErrorValidation.ErrorTest(ErrorValidation.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- ErrorTest -->
  <testcase classname="testcases.ErrorValidation" name="ProductErrorValidation" time="3.578">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.ErrorValidation.ProductErrorValidation(ErrorValidation.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- ErrorValidation Test -->
